### ISSUE TITLE
Practica 9 - Diagrama de Secuencias 

### ISSUE THREAD

**Issue by Diego047** [SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-de-irving#3]
[Practica9 Diagramas de  secuencia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-de-irving/files/10199276/Practica9.Diagramas.de.secuencia.pdf)

**Comment by ang3-l32** [comment]
49

**Comment by josealfredo79** [comment]
Bien hecho...
